/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "Basic_settings.h"

//para debug VER CLASES DE 55 A 56 DEL CURSO
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#define Port_test	(Port_D)
#define Pin_test	(Pin_2)

int main(void)
{

	SetPinMode(Port_B, Pin_8, Output);
	SetPinMode(Port_B, Pin_9, Output);
	SetPinMode(Port_C, Pin_13, Input);
	GPIO_SET_Output_Byte(Op_PortC);

	uint8_t sec_4bit_linea[8]={9,8,12,4,6,2,3,1};
	uint8_t sec_8bit_linea[16]={129,128,192,64,96,32,48,16,24,8,12,4,6,2,3,1};

	int8_t start_4bit=7;
	int8_t start_8bit=15;
	uint8_t sentido =0;

	GPIO_DigitalWrite(Port_B, Pin_8, High);
	GPIO_DigitalWrite(Port_B, Pin_9, Low);

	while(1){

		if(GPIO_DigitalRead(Port_C,Pin_13) == Low){

			GPIO_DigitalWrite(Port_B, Pin_8, sentido);
			GPIO_DigitalWrite(Port_B, Pin_9, !sentido);
			sentido = !sentido;
			while(GPIO_DigitalRead(Port_C,Pin_13) == Low){

			}
		}

		if(sentido==0){
			GPIO_Write_Byte(Op_PortC, sec_8bit_linea[start_8bit]);
			start_8bit++;
			if(start_8bit>15){
				start_8bit=0;
			}
			Delay(10);
		}else{
			GPIO_Write_Byte(Op_PortC, sec_8bit_linea[start_8bit]);
			start_8bit--;
			if(start_8bit<0){
				start_8bit=15;
			}
			Delay(10);

		}

	};

}

